#!/bin/bash

set -x

SCRIPT_DIR="$(dirname "$(realpath "$0")")"
cd "$SCRIPT_DIR/.."

# run mypy checks
uv run --directory microcoin --dev --with pip \
  python -m mypy --install-types --non-interactive --cache-fine-grained --sqlite-cache .